services:
    polar-defense:
        build: .
        container_name: polar-defense
        restart: unless-stopped
        networks:
            - web
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.polar-defense.rule=Host(`polar-defender.kyd.au`)"
            - "traefik.http.routers.polar-defense.entrypoints=websecure"
            - "traefik.http.routers.polar-defense.tls.certresolver=myresolver"
            - "traefik.http.services.polar-defense.loadbalancer.server.port=80"

networks:
    web:
        external: true
