services:
    polar-defender:
        build: .
        container_name: polar-defender
        restart: unless-stopped
        networks:
            - traefik_default
        labels:
            - "traefik.enable=true"
            - "traefik.docker.network=traefik_default"
            - "traefik.http.routers.polar-defender.rule=Host(`polar-defender.kyd.au`)"
            - "traefik.http.routers.polar-defender.entrypoints=websecure"
            - "traefik.http.routers.polar-defender.tls.certresolver=le"
            - "traefik.http.routers.polar-defender.middlewares=polar-defender-compress"
            - "traefik.http.middlewares.polar-defender-compress.compress=true"
            - "traefik.http.services.polar-defender.loadbalancer.server.port=80"

networks:
    traefik_default:
        external: true
